ismeet010/Magic-Of-CSS

happy-toggle/happy.css
happy-toggle/index.html

Heya, I have this fun little thing from a couple years ago, but I still look back to this on a regular basis to remind me to have fun with CSS, and what great things can be done with pure styling. I think this is kinda perfect for a repo like this that is all about the fun of CSS. c:

Happiness Toggle

---

Bicycle Using HTML5 and CSS3/index.html
Bicycle Using HTML5 and CSS3/style.css

- Create Bicycle as part of Hacktoberfest 2022 which fixes issue #2 
Kindly add 'hacktoberfest-accepted' tag and merge PR. Thanks!

Feat: Add Bicycle Using HTML5 and CSS3

---

image hover/index.html
image hover/style.css

Added various types of animation effects that can be applied on hovering an image. Kindly accept this under Hacktoberfest. TIA.

Added Image hovering Effects

---

Birds Flyby animation/birds.css
Birds Flyby animation/index.html

Pull request for issue #5 
pls add Hactober fest tags before merge

Simple animation of birds flyby using CSS and HTML

---

Ring wave animation/index.html
Ring wave animation/style.css

output
https://user-images.githubusercontent.com/52989607/151699708-2b9d348f-c91f-49c1-8b29-9a299d64e3d2.mp4

ring wave animation

---

Ring wave animation/index.html
Ring wave animation/style.css
Wires pull SVG loader/index.html
Wires pull SVG loader/script.js
Wires pull SVG loader/style.css

output
https://user-images.githubusercontent.com/52989607/193997632-0f9bd198-5d6a-4079-8af2-5194ab51fcdf.mp4

Wire pull animation

---

Contributing.md
README.md

**Issue #13**
- Added **Contributing.md**
- Added **Socalify element to README.md file.**
- **Corrected the link** for HacktoberFest image

Made README for appealing with proper instructions in Contributing.md

---

Contributing.md
LICENSE.md
README.md

**Issue #20**
- Added the **contribution section** in README.md file which is updated automatically.
- Added the **Copyright Logo for the project.**
- Added **additional help links** to basics of git in **Contributing.md**
- Added MIT License in **LICENSE.md** file with **owner as ismeet010.**

[docs]: Improvement in README.md, Contributing.md and LICENSE.md file Issue#20

---

click_counter/counter.css
click_counter/counter.html
click_counter/counter.js

Added click_counter for hacktober fest

added click_counter

---

DNA_using_CSS/dna.html
DNA_using_CSS/script.js
DNA_using_CSS/style.css

I added a css and html programme which will create a DNA.

Added a css file of DNA

---

Typing effects/index.html
Typing effects/styles.css

Typing effect with variable speed control closes the issue #33

Added the files for typing animation

---

LoginFormAnimation/index.html
LoginFormAnimation/style.css

#hacktoberfest #hacktoberfest2022
https://user-images.githubusercontent.com/82941619/194849242-9f79f3dd-abf7-4306-b542-6c5836929445.mp4

Login Form Animation

---

QuizApp/index.html
QuizApp/quiz.css
QuizApp/quiz.js

A simple quiz webapp on github made using html,css and js.
I learned about arrays,dom manipulation and animations through this project

added quizapp

---

hover_color_animation/index.html
hover_color_animation/script.js
hover_color_animation/style.css

I added a new page with button hover animations. It's simple but very nice.

added new page with hover animations

---

css-loaders-tutorial-starter-files/README.md
css-loaders-tutorial-starter-files/index.html
css-loaders-tutorial-starter-files/styles.css

added spinner animation

---

3dFlipCardAnimation/index.html
3dFlipCardAnimation/style.css

Fixes #44 
https://user-images.githubusercontent.com/96621669/196097395-b1ea81ca-c843-4c73-a1d2-5bc26c733b4a.mov

Added 3d Flip Card Animation

---

Carousel of pictures/index.html
Carousel of pictures/script.js
Carousel of pictures/style.css

Folder containing code of carousel made using vanilla JS, HTML and CSS.
Some pics of the carousel are:
Please merge this PR and consider it for hacktoberfest.

Added carousel of pictures made using HTML,CSS,JS

---

Text Water Effect/index.html
Text Water Effect/style.css

Water in Text animation has been created can you check the changes and merge.....

Created Text in Water Effect

---

changing emoji rating/index.html
changing emoji rating/style.css

Fixes #52 
https://user-images.githubusercontent.com/96621669/196247935-03073b70-e6fb-452f-b353-de949ffd1eea.mov

Added Emoji Rating animation

---

CSSTextReveal/index.html

CSS text reveal animation added

---

Tab-Component/index.html
Tab-Component/style.css

Hey!
Kindly review and merge my pull request. 
issue #67

Added Tab component 
